# Generated by Django 6.0 on 2026-01-02 08:09

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_phase', models.CharField(help_text='Current flow phase (e.g., q1_selection, q2_review)', max_length=50, verbose_name='current phase')),
                ('current_layer', models.IntegerField(default=1, help_text='Current layer number (1, 2, or 3)', verbose_name='current layer')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'questionnaire progress',
                'verbose_name_plural': 'questionnaire progress',
                'db_table': 'questionnaire_progress',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='idx_prog_user'), models.Index(fields=['user', 'question'], name='idx_prog_user_q')],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), help_text='Array of selected option UUIDs (supports multi-select)')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When user confirmed this layer', null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('layer', models.ForeignKey(help_text='Layer this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='content.layer')),
                ('question', models.ForeignKey(help_text='Question this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='content.question')),
                ('user', models.ForeignKey(help_text='User who submitted this response', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
                'db_table': 'responses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_resp_user'), models.Index(fields=['question'], name='idx_resp_question'), models.Index(fields=['user', 'question'], name='idx_resp_user_q')],
                'unique_together': {('user', 'question', 'layer')},
            },
        ),
    ]
