# Generated by Django 6.0 on 2026-01-05 07:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_option_image_url'),
        ('responses', '0001_initial'),
        ('teams', '0004_unique_team_name_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('text', 'Text')], default='video', max_length=10, verbose_name='recording type')),
                ('media_url', models.URLField(blank=True, help_text='Cloudinary URL for video/audio file', max_length=500, null=True, verbose_name='media URL')),
                ('media_public_id', models.CharField(blank=True, help_text='Cloudinary public ID for media management', max_length=255, null=True, verbose_name='media public ID')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image URL (for video)', max_length=500, null=True, verbose_name='thumbnail URL')),
                ('text_content', models.TextField(blank=True, help_text='Text response content', null=True, verbose_name='text content')),
                ('description', models.CharField(blank=True, help_text='Short description or caption', max_length=500, null=True, verbose_name='description')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds (for video/audio)', null=True, verbose_name='duration')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='file size')),
                ('is_visible_to_team', models.BooleanField(default=True, help_text='Whether team members can see this recording', verbose_name='visible to team')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(help_text='Question this recording is for', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='content.question')),
                ('team', models.ForeignKey(blank=True, help_text='Team this recording belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='teams.team')),
                ('user', models.ForeignKey(help_text='User who created this recording', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recording',
                'verbose_name_plural': 'recordings',
                'db_table': 'recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingAffirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('affirming_user', models.ForeignKey(help_text='User giving the affirmation', on_delete=django.db.models.deletion.CASCADE, related_name='affirmations_given', to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affirmations', to='responses.recording')),
            ],
            options={
                'verbose_name': 'recording affirmation',
                'verbose_name_plural': 'recording affirmations',
                'db_table': 'recording_affirmations',
            },
        ),
        migrations.CreateModel(
            name='RecordingComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='comment text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='responses.recording')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recording comment',
                'verbose_name_plural': 'recording comments',
                'db_table': 'recording_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='responses.recording')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recording reaction',
                'verbose_name_plural': 'recording reactions',
                'db_table': 'recording_reactions',
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['user'], name='idx_rec_user'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['question'], name='idx_rec_question'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['team'], name='idx_rec_team'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['user', 'question'], name='idx_rec_user_q'),
        ),
        migrations.AlterUniqueTogether(
            name='recordingaffirmation',
            unique_together={('affirming_user', 'recording')},
        ),
        migrations.AlterUniqueTogether(
            name='recordingreaction',
            unique_together={('user', 'recording')},
        ),
    ]
