# Generated by Django 6.0 on 2025-12-29 04:36

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='User email address (used for login)', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('google_id', models.CharField(blank=True, help_text='Google OAuth identifier for social login', max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('display_name', models.CharField(help_text='Name shown to other users', max_length=255, verbose_name='display name')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='last name')),
                ('profile_photo_url', models.TextField(blank=True, default='', help_text='Cloudinary URL for profile photo (Batch 2)', verbose_name='profile photo URL')),
                ('bio', models.TextField(blank=True, default='', help_text='User biography (Batch 5)', verbose_name='bio')),
                ('pronouns', models.CharField(blank=True, default='', help_text='User pronouns (Batch 5)', max_length=100, verbose_name='pronouns')),
                ('is_hcw', models.BooleanField(default=False, help_text='User attestation that they are a healthcare worker (data collection only)', verbose_name='is healthcare worker')),
                ('hcw_attested_at', models.DateTimeField(blank=True, help_text='When the user attested to being an HCW', null=True, verbose_name='HCW attestation timestamp')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the user has verified their email address', verbose_name='email verified')),
                ('email_verification_token', models.CharField(blank=True, default='', help_text='Token sent in verification email', max_length=255, verbose_name='email verification token')),
                ('email_verification_sent_at', models.DateTimeField(blank=True, help_text='When the verification email was sent', null=True, verbose_name='email verification sent at')),
                ('password_reset_token', models.CharField(blank=True, default='', help_text='Token for password reset flow', max_length=255, verbose_name='password reset token')),
                ('password_reset_expires_at', models.DateTimeField(blank=True, help_text='When the password reset token expires', null=True, verbose_name='password reset expires at')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user account was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the user account was last updated', verbose_name='updated at')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='When the user last logged in', null=True, verbose_name='last login at')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the user account was soft deleted (30-day retention)', null=True, verbose_name='deleted at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_users_email'), models.Index(fields=['google_id'], name='idx_users_google_id'), models.Index(fields=['deleted_at'], name='idx_users_deleted_at')],
            },
        ),
    ]
