# Generated by Django 6.0 on 2025-12-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='User date of birth (optional)', null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', help_text='User location/city (optional)', max_length=255, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='User phone number (optional)', max_length=20, verbose_name='phone number'),
        ),
    ]
