# Generated by Django 6.0 on 2025-12-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date_user_location_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_code',
            field=models.CharField(blank=True, default='', help_text='6-digit verification code for password change', max_length=6, verbose_name='password change verification code'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_change_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the password change verification code expires (15 minutes)', null=True, verbose_name='password change code expires at'),
        ),
    ]
