# Generated by Django 6.0 on 2026-01-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_change_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restoration_code',
            field=models.CharField(blank=True, default='', help_text='6-digit verification code for account restoration', max_length=6, verbose_name='account restoration code'),
        ),
        migrations.AddField(
            model_name='user',
            name='restoration_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the restoration verification code expires (1 hour)', null=True, verbose_name='restoration code expires at'),
        ),
    ]
