# Generated by Django 6.0 on 2026-01-02 08:09

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_number', models.IntegerField(help_text='Layer number (1, 2, or 3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='layer number')),
                ('layer_title', models.CharField(help_text='e.g., YOUR POSITION, YOUR CHALLENGES, YOUR MIND-CHANGER', max_length=255, verbose_name='layer title')),
                ('layer_question', models.TextField(help_text='The question text for this layer', verbose_name='layer question')),
                ('selection_type', models.CharField(choices=[('single', 'Single-select'), ('multi', 'Multi-select')], max_length=20, verbose_name='selection type')),
                ('max_selections', models.IntegerField(blank=True, help_text='Maximum selections for multi-select (e.g., 2)', null=True, verbose_name='max selections')),
                ('components_at_selection', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, help_text='Components shown at selection (e.g., [C1, C3])')),
                ('components_at_confirmation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default=list, help_text='Components shown at confirmation (e.g., [C2, C4, C5])')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'layer',
                'verbose_name_plural': 'layers',
                'db_table': 'layers',
                'ordering': ['question', 'layer_number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(help_text='Question ID (e.g., Q10A, Q10B, Q11, Q12)', max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short question title', max_length=255, verbose_name='title')),
                ('question_text', models.TextField(help_text='The actual question asked to users', verbose_name='question text')),
                ('category', models.CharField(blank=True, default='', help_text='Question category (e.g., UHCDA Priority Values)', max_length=50, verbose_name='category')),
                ('display_order', models.IntegerField(help_text='Order in which question appears', verbose_name='display order')),
                ('batch_number', models.IntegerField(help_text='Which batch this question belongs to (1-10)', verbose_name='batch number')),
                ('uhcda_section', models.CharField(blank=True, default='', help_text='UHCDA legal section reference', max_length=50, verbose_name='UHCDA section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'questions',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['batch_number'], name='idx_q_batch'), models.Index(fields=['display_order'], name='idx_q_order')],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_number', models.IntegerField(help_text='Option number within question (1-11)', verbose_name='option number')),
                ('option_text', models.TextField(help_text='C1 text - Form Response Option', verbose_name='option text')),
                ('display_order', models.IntegerField(verbose_name='display order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.layer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.question')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
                'db_table': 'options',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='content.question'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('C1', 'C1: Form Response Option'), ('C2', 'C2: Why This Matters'), ('C3', 'C3: How This Sounds'), ('C4', 'C4: Research Evidence'), ('C5', 'C5: Decision Impact'), ('C6', "C6: What You're Fighting For"), ('C7', 'C7: Cooperative Learning'), ('C8', 'C8: Interdependency at Work'), ('C9', 'C9: Barriers to Access'), ('C10', 'C10: Reflection Guidance'), ('C11', 'C11: Care Team Affirmation')], max_length=5, verbose_name='component type')),
                ('component_text', models.TextField(verbose_name='component text')),
                ('character_count', models.IntegerField(blank=True, null=True, verbose_name='character count')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='content.option')),
            ],
            options={
                'verbose_name': 'component',
                'verbose_name_plural': 'components',
                'db_table': 'components',
                'indexes': [models.Index(fields=['option'], name='idx_comp_option'), models.Index(fields=['component_type'], name='idx_comp_type')],
                'unique_together': {('option', 'component_type')},
            },
        ),
        migrations.CreateModel(
            name='PersonalPatternRecognition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_name', models.CharField(help_text='Descriptive pattern name', max_length=100, verbose_name='pattern name')),
                ('l1_option', models.IntegerField(verbose_name='L1 option number')),
                ('l2_options', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='L2 option numbers (array for multi-select)')),
                ('l3_option', models.IntegerField(verbose_name='L3 option number')),
                ('ppr_text', models.TextField(help_text='440-550 characters, target 480', verbose_name='PPR text')),
                ('character_count', models.IntegerField(blank=True, null=True, verbose_name='character count')),
                ('coverage_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated % of users this pattern covers', max_digits=5, null=True, verbose_name='coverage percentage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppr_patterns', to='content.question')),
            ],
            options={
                'verbose_name': 'personal pattern recognition',
                'verbose_name_plural': 'personal pattern recognitions',
                'db_table': 'personal_pattern_recognition',
                'indexes': [models.Index(fields=['question'], name='idx_ppr_question')],
            },
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question'], name='idx_opt_question'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['layer'], name='idx_opt_layer'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['display_order'], name='idx_opt_order'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'option_number')},
        ),
        migrations.AddIndex(
            model_name='layer',
            index=models.Index(fields=['question'], name='idx_layer_question'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('question', 'layer_number')},
        ),
    ]
