# Generated by Django 6.0 on 2026-01-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text='Cloudinary URL for component image/media', verbose_name='image URL'),
        ),
        migrations.AddField(
            model_name='component',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='', help_text='Type of media attached to this component', max_length=20, verbose_name='media type'),
        ),
        migrations.AddField(
            model_name='layer',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text='Cloudinary URL for layer image', verbose_name='image URL'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.TextField(blank=True, default='', help_text='Cloudinary URL for question card image', verbose_name='image URL'),
        ),
        migrations.AddField(
            model_name='question',
            name='thumbnail_url',
            field=models.TextField(blank=True, default='', help_text='Cloudinary URL for question thumbnail (auto-generated)', verbose_name='thumbnail URL'),
        ),
    ]
