# Generated by Django 6.0 on 2026-01-06 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('team_invitation', 'Team Invitation'), ('invitation_accepted', 'Invitation Accepted'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('role_changed', 'Role Changed'), ('affirmation', 'Affirmation Received'), ('question_completed', 'Question Completed'), ('chat_message', 'Chat Message'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='communicati_user_id_229fc2_idx'), models.Index(fields=['user', 'read_at'], name='communicati_user_id_438b03_idx')],
            },
        ),
    ]
