# Generated by Django 6.0 on 2025-12-29 04:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the team', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the care team', max_length=255, verbose_name='team name')),
                ('description', models.TextField(blank=True, default='', help_text='Team description (Batch 8)', verbose_name='description')),
                ('avatar_url', models.TextField(blank=True, default='', help_text='Cloudinary URL for team avatar (Batch 4)', verbose_name='avatar URL')),
                ('team_level', models.IntegerField(blank=True, choices=[(1, 'Level 1: Immediate Family'), (2, 'Level 2: Family Back Home'), (3, 'Level 3: Local Chosen Family')], help_text='Team level for multi-team support (MVP, not Pre-MVP)', null=True, verbose_name='team level')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the team was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the team was last updated', verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the team was soft deleted (Batch 9+10)', null=True, verbose_name='deleted at')),
                ('created_by', models.ForeignKey(help_text='User who created this team (team leader)', on_delete=django.db.models.deletion.RESTRICT, related_name='teams_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'db_table': 'teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the membership', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member'), ('witness', 'Witness')], help_text='Role within the team (leader/member/witness)', max_length=20, verbose_name='role')),
                ('is_default_guardian', models.BooleanField(default=False, help_text='Leader is default guardian for this member', verbose_name='is default guardian')),
                ('is_default_emergency_contact', models.BooleanField(default=False, help_text='Leader is default emergency contact for this member', verbose_name='is default emergency contact')),
                ('invitation_token', models.CharField(blank=True, help_text='Unique token for invitation link', max_length=255, null=True, unique=True, verbose_name='invitation token')),
                ('invitation_sent_at', models.DateTimeField(blank=True, help_text='When the invitation was sent', null=True, verbose_name='invitation sent at')),
                ('invitation_expires_at', models.DateTimeField(blank=True, help_text='When the invitation expires', null=True, verbose_name='invitation expires at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('left', 'Left')], default='pending', help_text='Membership status', max_length=20, verbose_name='status')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When the user accepted the invitation', null=True, verbose_name='joined at')),
                ('left_at', models.DateTimeField(blank=True, help_text='When the user left the team', null=True, verbose_name='left at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the membership was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the membership was last updated', verbose_name='updated at')),
                ('emergency_contact_override', models.ForeignKey(blank=True, help_text='Member-specified emergency contact (overrides leader default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_contact_for_memberships', to=settings.AUTH_USER_MODEL)),
                ('guardian_override', models.ForeignKey(blank=True, help_text='Member-specified guardian (overrides leader default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_for_memberships', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='The team this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
                ('user', models.ForeignKey(help_text='The user who is a member of this team', on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team membership',
                'verbose_name_plural': 'team memberships',
                'db_table': 'team_memberships',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_by'], name='idx_teams_created_by'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['deleted_at'], name='idx_teams_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team'], name='idx_memberships_team'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user'], name='idx_memberships_user'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['invitation_token'], name='idx_memberships_invitation_token'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['status'], name='idx_memberships_status'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'witness'), _negated=True), models.Q(('guardian_override__isnull', True), ('guardian_override__isnull', True)), _connector='OR'), name='witness_cannot_be_agent', violation_error_message='Witness cannot be designated as guardian or emergency contact'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'user')},
        ),
    ]
