# Generated by Django 6.0 on 2025-12-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='idx_tm_team',
            old_name='idx_memberships_team',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='idx_tm_user',
            old_name='idx_memberships_user',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='idx_tm_invite_token',
            old_name='idx_memberships_invitation_token',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='idx_tm_status',
            old_name='idx_memberships_status',
        ),
    ]
