# Generated by Django 6.0 on 2026-01-03 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_idx_memberships_team_idx_tm_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the pending invitation', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the person being invited', max_length=254, verbose_name='email')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member'), ('witness', 'Witness')], default='member', help_text='Role they will have when they join', max_length=20, verbose_name='role')),
                ('message', models.TextField(blank=True, default='', help_text='Custom message from the inviter', verbose_name='message')),
                ('invitation_token', models.CharField(help_text='Unique token for the signup invitation link', max_length=255, unique=True, verbose_name='invitation token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the invitation was sent', verbose_name='created at')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires', verbose_name='expires at')),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='pending_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text='The team they are being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='pending_invitations', to='teams.team')),
            ],
            options={
                'verbose_name': 'pending invitation',
                'verbose_name_plural': 'pending invitations',
                'db_table': 'pending_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_pi_email'), models.Index(fields=['invitation_token'], name='idx_pi_token'), models.Index(fields=['team'], name='idx_pi_team')],
                'unique_together': {('email', 'team')},
            },
        ),
    ]
