# Generated by Django 6.0 on 2026-01-04 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_pending_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('created_by', 'name'), name='unique_team_name_per_user'),
        ),
    ]
